name: Deploy FastAPI to MIG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/927058090633/locations/global/workloadIdentityPools/mig-github-ci-cd-work-load/providers/github-provider
          service_account: mig-github-ci-cd@first-rank-coders.iam.gserviceaccount.com
          audience: https://iam.googleapis.com/projects/927058090633/locations/global/workloadIdentityPools/mig-github-ci-cd-work-load/providers/github-provider
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy new Instance Template
        run: |
          gcloud compute instance-templates create fastapi-template-${{ github.run_number }} \
          --machine-type=e2-micro \
          --metadata-from-file startup-script=fastapi-mig-ci-cd/startup.sh

      - name: Update MIG
        run: |
          gcloud compute instance-groups managed set-instance-template fastapi-mig-group \
          --template fastapi-template-${{ github.run_number }} \
          --zone us-central1-c
