name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP using Workload Identity Federation
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/927058090633/locations/global/workloadIdentityPools/fastapi-docker-github-action/providers/fast-api-docker-github-provider
          service_account: fastapi-docker-githubaction@first-rank-coders.iam.gserviceaccount.com

      # Install gcloud SDK
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Configure Docker for Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Build Docker Image
      - name: Build Docker Image
        run: |
          cd fastapi-mig-ci-cd-docker
          docker build -t us-central1-docker.pkg.dev/first-rank-coders/mig-docker-github-fastapi/fastapi:latest .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/first-rank-coders/mig-docker-github-fastapi/fastapi:latest

      # Create Instance Template
      - name: Create Instance Template
        run: |
          gcloud compute instance-templates create fastapi-docker-github-${{ github.run_number }} \
          --machine-type=e2-micro \
          --service-account=fastapi-docker-githubaction@first-rank-coders.iam.gserviceaccount.com \
          --scopes=https://www.googleapis.com/auth/cloud-platform \
          --tags=allow-fastapi \
          --metadata-from-file startup-script=fastapi-mig-ci-cd/startup.sh

      # Update Managed Instance Group Template
      - name: Update MIG Template
        run: |
          gcloud compute instance-groups managed set-instance-template fastapi-docker-mig \
          --template fastapi-docker-github-${{ github.run_number }} \
          --zone us-central1-c

      # Rolling Update Instances
      - name: Rolling Update MIG
        run: |
          gcloud compute instance-groups managed rolling-action replace fastapi-docker-mig \
          --zone us-central1-c
